server:
  port: ${PORT:8083}

spring:
  application:
    name: bookcomposite

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: https://eurekaserver-0ha1.onrender.com/eureka/
